# Generated by Django 5.2.1 on 2026-04-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum confirmed registrations. Leave blank for unlimited.', null=True),
        ),
    ]
